version: "3.9"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invynest
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/17/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d invynest"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  pg_data: